name: Hassfest

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  validate:
    name: Validate with Hassfest
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Run Hassfest validation
        uses: home-assistant/actions/hassfest@master
